### PR TITLE
Update terminology.rst

### PR DESCRIPTION
**Pull request by reece**
The biological consequence is likely not strictly a criterion for a gene fusion.

### CODE REVIEW

**Comment by ahwagner** [comment]
Thank you for the feedback @reece!

One of the earliest discussions in this group was on the topic of what is and _is not_ a gene fusion, and the consensus was that rearrangements that disrupted a gene (causing a null / non-transcribed product) were not a gene fusion. This section of the text was designed to help capture that requirement.

However, your description of this segment of the definition as "biological consequence" has me thinking this could be improved upon. I think your revision, with additional text to define the constraint about null / disrupted genes, would be an improvement. I will add those changes to the PR and will run this by the gene fusions group for approval before merge.

**Comment by reece** [comment]
Okay, as I read the terminology, I'm confused about the relationship between gene fusions and rearrangements. The paragraph "Similar genetic variations involving...presence of specific gene fusions." seems relevant, but not specific enough for me to grok.

The main reason for raising this issue is to encourage the separation representation from annotation, and I cannot tell whether the terminology is doing that. If the definition of an entity, such as a Gene Fusion, depends on known associated information, such as functional consequences, then that raises the consideration that one cannot talk about the entity before the associated information is known or when the associated information becomes invalidated. (Imagine, for example, what it might mean for a thing that we call a Gene Fusion to be downgraded when its functional significance is disproved.)

I think it might be helpful to distinguish the molecular change from the annotation, perhaps like this:
- First, define Rearrangements as structural changes in sequence. Enumerate the types of those as you already do. Make chimeric transcript fusions a type of Rearrangement rather than a type of fusion (because it's a structural property, not a functional one.)
- Then, define Gene Fusions as Rearrangements that involve gene regions (transcript or regulatory elements) *that also have a known consequence*
- Then, consider whether Rearrangements might move to VRS since it's a representational concept. That would enable VICC fusions to stick to the meaning of variation rather than delve into the molecular structure of the subject of annotations.

These changes would enable the community to talk about molecular changes (Rearrangements) when that narrow fact was intended, and to discuss classes of these based on function.

**Comment by ahwagner** [comment]
Hey @reece. You and I are on the same page with respect to goals. Another annotation that is boiled into gene fusions is in the first part of the definition: "_joining of two or more genes_". So chimeric transcripts emerging from ITDs, etc. are _not_ gene fusions, though they are reported by the same tools that call fusions (e.g., cicero) and would benefit from a shared molecular representation. This is also a major reason I think we shouldn't use "fusion transcript" for HGVS and should rename it as discussed in HGVSnomenclature/HVNC#13.

I have difficulty getting behind _rearrangement_ as the common descriptive name for concatenated sequence segments, as a chimeric transcript product that is formed by trans-splicing or read-through is not associated with any genomic rearrangement. Like you, I do think there is a common structure for representing concatenated sequences that is relevant to both rearrangements and chimeric transcripts, and that is what we would take to VRS. It may also end up aligned with HGVS as an _adjoined sequence_ / _concatenated sequence_ class.

**Comment by ahwagner** [comment]
Thank you for the feedback, @reece. I made a number of clarifying revisions considering your comments, and will be merging this into our response branch for the HUGO committee chairs.

**Pull request merged**
